name:  AWS Evidence Collection
on:
  workflow_dispatch:
jobs:
  fetch_and_save_scans:
    runs-on: ubuntu-latest
    permissions:                
     contents: write          
     pull-requests: write      
    env: 
      CI_COMMIT_MESSAGE: AWS Evidence
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Environment Variables
      uses: .github/variables-federal.yml@main

    - name: Environment Variables
      uses: .github/variables-commercial.yml@main
      
    - name: Create Tenable evidence artifacts directory
      run: mkdir -p evidence-artifacts/federal/

    - name: Create Tenable evidence artifacts directory
      run: mkdir -p evidence-artifacts/commercial/

    - name: Run AWS Evidence Collection Scripts
      working-directory: src/collection/aws
      run: |
          python |
          python

    - name: Commit & Push
      uses: ./.github/workflows/actions/commit-and-push.yml

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ${{ env.CI_COMMIT_MESSAGE }}

        
        
