name:  Tenable Commercial
on:
  workflow_dispatch:
jobs:
  fetch_and_save_scans:
    runs-on: ubuntu-latest
    permissions:                
     contents: write          
     pull-requests: write      
    env: 
      CI_COMMIT_MESSAGE: New Tenable Scan Results
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Environment Variables
      uses: .github/variables-commercial.yml@main

    - name: List evidence-collection directory contents
      run: ls -la src/evidence-collection/
    - name: Create Tenable evidence artifacts directory
      run: mkdir -p ../../../evidence-artifacts/commercial/tenable

    - name: Debug API Key
      run: echo "Tenable Access Key:${{ secrets.CORP_TENABLE_ACCESS_KEY }}"
    - name: Debug environment variables
      run: printenv | grep TIO
    - name: Debug API Keys
      run: |
       echo "Tenable Access Key: ${{ secrets.CORP_TENABLE_ACCESS_KEY }}"
       echo "Tenable Secret Key: ${{ secrets.CORP_TENABLE_SECRET_KEY }}"

    - name: Run Tenable Scan Script
      env:
        TIO_ACCESS_KEY: ${{ secrets.CORP_TENABLE_ACCESS_KEY }}
        TIO_SECRET_KEY: ${{ secrets.CORP_TENABLE_SECRET_KEY }}
      working-directory: src/poam
      run: python commercial-tenable.py --download-path ../../../evidence-artifacts/commercial/tenable

    - name: Commit & Push
      uses: ./.github/workflows/actions/commit-and-push.yml
      
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ${{ env.CI_COMMIT_MESSAGE }}

    - name: Upload Commercial Tenable Reports
      uses: actions/upload-artifact@v3
      with:
        name: tenable-reports
        path: evidence-artifacts/commercial/tenable
        
