name: Commercial Environment Variables Setup
on: 
  workflow_dispatch:
jobs:
  commercial:
    name: Commercial Environment Setup
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials for commercial
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEVOPS_CORP_AUTOMATION_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEVOPS_CORP_AUTOMATION_AWS_SECRET }}
          aws-region: us-east-1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use a specific Python version

      - name: Prepare Environment
        id: prep
        run: /bin/bash .github/prep.sh

      - name: Set environment variables for additional secrets
        env:
          TRINET_API_KEY: ${{ secrets.TRINET_API_KEY }}
          TRINET_API_SECRET: ${{ secrets.TRINET_API_SECRET }}
          OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
          OKTA_API_TOKEN: ${{ secrets.OKTA_API_TOKEN }}
          ATLASSIAN_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
          ATLASSIAN_EMAIL: ${{ secrets.JIRA_EMAIL }}
          ATLASSIAN_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          CORP_TIO_ACCESS_KEY: ${{ secrets.CORP_TENABLE_ACCESS_KEY }}
          CORP_TIO_SECRET_KEY: ${{ secrets.CORP_TENABLE_SECRET_KEY }}

      - name: Git Global Config
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "actions@github.com"
